version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app-new"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1vmbx0ody1986"
s3_prefix = "sam-app-new"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
